# Generated by Django 4.2.4 on 2023-08-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_is_finished_remove_task_is_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-due_date',)},
        ),
    ]
